export interface MeaningSource {
	id: string;
	name: string;
}

export const MEANING_SOURCES: readonly MeaningSource[] = [
	{ id: "social-commitment", name: "Social commitment" },
	{ id: "religiosity", name: "Religiosity" },
	{ id: "unity-with-nature", name: "Unity with nature" },
	{ id: "self-knowledge", name: "Self-knowledge" },
	{ id: "health", name: "Health" },
	{ id: "generativity", name: "Generativity" },
	{ id: "spirituality", name: "Spirituality" },
	{ id: "challenge", name: "Challenge" },
	{ id: "individualism", name: "Individualism" },
	{ id: "power", name: "Power" },
	{ id: "development", name: "Development" },
	{ id: "success", name: "Success" },
	{ id: "freedom", name: "Freedom" },
	{ id: "knowledge", name: "Knowledge" },
	{ id: "creativity", name: "Creativity" },
	{ id: "tradition", name: "Tradition" },
	{ id: "practicality", name: "Practicality" },
	{ id: "moral", name: "Moral" },
	{ id: "reason", name: "Reason" },
	{ id: "community", name: "Community" },
	{ id: "fun", name: "Fun" },
	{ id: "love", name: "Love" },
	{ id: "comfort", name: "Comfort" },
	{ id: "care", name: "Care" },
	{ id: "attentiveness", name: "Attentiveness" },
	{ id: "harmony", name: "Harmony" },
];

export interface MeaningStatement {
	id: string;
	// Corresponds to MEANING_SOURCES[].id.
	meaningId: string;
	statement: string;
	isPrimary: boolean;
}

// ID numbering based on The Sources of Meaning and Meaning in Life
// Questionnaire, Tatjana Schnell
export const MEANING_STATEMENTS: readonly MeaningStatement[] = [
	{
		id: "3",
		meaningId: "social-commitment",
		statement: "I intervene when I see injustice being done",
		isPrimary: true,
	},
	{
		id: "4",
		meaningId: "religiosity",
		statement: "Religion plays an important role in my life",
		isPrimary: false,
	},
	{
		id: "5",
		meaningId: "unity-with-nature",
		statement: "I feel very close to nature and the outdoors",
		isPrimary: false,
	},
	{
		id: "6",
		meaningId: "self-knowledge",
		statement: "To understand myself and my behaviour is important for me",
		isPrimary: true,
	},
	{
		id: "7",
		meaningId: "health",
		statement: "I pay great attention to my health",
		isPrimary: false,
	},
	{
		id: "8",
		meaningId: "generativity",
		statement: "You should leave something behind for future generations",
		isPrimary: false,
	},
	{
		id: "9",
		meaningId: "spirituality",
		statement: "Everyone's fate is predestined",
		isPrimary: false,
	},
	{
		id: "10",
		meaningId: "challenge",
		statement: "I need a bit of risk and excitement in my life",
		isPrimary: false,
	},
	{
		id: "11",
		meaningId: "individualism",
		statement: "The most important goal in my life is personal fulfilment",
		isPrimary: false,
	},
	{
		id: "12",
		meaningId: "challenge",
		statement: "I accept the challenges life throws at me",
		isPrimary: false,
	},
	{
		id: "13",
		meaningId: "development",
		statement: "Life for me means striving for growth and development",
		isPrimary: false,
	},
	{
		id: "14",
		meaningId: "success",
		statement: "Success is what matters to me",
		isPrimary: false,
	},
	{
		id: "15",
		meaningId: "freedom",
		statement: "I want to be free and independent",
		isPrimary: false,
	},
	{
		id: "16",
		meaningId: "knowledge",
		statement: "I have a great thirst for knowledge",
		isPrimary: false,
	},
	{
		id: "17",
		meaningId: "creativity",
		statement: "Picasso was right saying that the most important things in life are to be creative and imaginative",
		isPrimary: true,
	},
	{
		id: "18",
		meaningId: "tradition",
		statement: "Leading an ordered life is important",
		isPrimary: false,
	},
	{
		id: "19",
		meaningId: "practicality",
		statement: "I need to see clear results at the end of a working day",
		isPrimary: false,
	},
	{
		id: "20",
		meaningId: "moral",
		statement: "Good manners are important to me",
		isPrimary: false,
	},
	{
		id: "21",
		meaningId: "reason",
		statement: "Problems can only be solved rationally",
		isPrimary: false,
	},
	{
		id: "22",
		meaningId: "community",
		statement: "We should spend our lives in the company of others",
		isPrimary: false,
	},
	{
		id: "23",
		meaningId: "fun",
		statement: "Having fun is the most important thing in life",
		isPrimary: false,
	},
	{
		id: "24",
		meaningId: "love",
		statement: "I take a great deal of time on matters of love and romance",
		isPrimary: true,
	},
	{
		id: "25",
		meaningId: "comfort",
		statement: "People should spoil themselves regularly",
		isPrimary: true,
	},
	{
		id: "26",
		meaningId: "care",
		statement: "I am a caring person",
		isPrimary: false,
	},
	{
		id: "27",
		meaningId: "attentiveness",
		statement: "Transitions from one phase of life to another need to be celebrated",
		isPrimary: false,
	},
	{
		id: "28",
		meaningId: "harmony",
		statement: "A feeling of harmony is very important in my life",
		isPrimary: false,
	},
	{
		id: "31",
		meaningId: "social-commitment",
		statement: "I am committed to seeing justice done",
		isPrimary: false,
	},
	{
		id: "32",
		meaningId: "religiosity",
		statement: "Prayer is important to me",
		isPrimary: false,
	},
	{
		id: "33",
		meaningId: "unity-with-nature",
		statement: "It is my aim to live in harmony with nature",
		isPrimary: true,
	},
	{
		id: "34",
		meaningId: "self-knowledge",
		statement: "Viewing myself critically is important to me",
		isPrimary: false,
	},
	{
		id: "35",
		meaningId: "health",
		statement: "I have a lifestyle that is good for my health",
		isPrimary: false,
	},
	{
		id: "36",
		meaningId: "generativity",
		statement: "I strive to do something for future generations",
		isPrimary: false,
	},
	{
		id: "37",
		meaningId: "spirituality",
		statement: "There are certain things in life I consider sacred",
		isPrimary: true,
	},
	{
		id: "38",
		meaningId: "challenge",
		statement: "People should try everything once",
		isPrimary: false,
	},
	{
		id: "39",
		meaningId: "individualism",
		statement: "Independence is immensely important to me",
		isPrimary: true,
	},
	{
		id: "40",
		meaningId: "challenge",
		statement: "I am a fighter",
		isPrimary: false,
	},
	{
		id: "41",
		meaningId: "development",
		statement: "I strive to fulfil my goals",
		isPrimary: false,
	},
	{
		id: "42",
		meaningId: "success",
		statement: "I admire people who are successful",
		isPrimary: false,
	},
	{
		id: "43",
		meaningId: "individualism",
		statement: "Independence means a lot to me",
		isPrimary: false,
	},
	{
		id: "44",
		meaningId: "knowledge",
		statement: "I like to question everything",
		isPrimary: true,
	},
	{
		id: "45",
		meaningId: "creativity",
		statement: "I like to be creative",
		isPrimary: false,
	},
	{
		id: "46",
		meaningId: "tradition",
		statement: "I like my life to follow a certain routine",
		isPrimary: false,
	},
	{
		id: "47",
		meaningId: "practicality",
		statement: "Instead of philosophising, people should take life by the horns",
		isPrimary: false,
	},
	{
		id: "48",
		meaningId: "moral",
		statement: "I have clear moral concepts",
		isPrimary: false,
	},
	{
		id: "49",
		meaningId: "reason",
		statement: "Reason is the measure of all things",
		isPrimary: true,
	},
	{
		id: "50",
		meaningId: "community",
		statement: "I take trouble to cultivate my relationships",
		isPrimary: false,
	},
	{
		id: "51",
		meaningId: "fun",
		statement: "A good sense of humour makes life easier",
		isPrimary: false,
	},
	{
		id: "52",
		meaningId: "love",
		statement: "I love to indulge in romantic feelings",
		isPrimary: false,
	},
	{
		id: "53",
		meaningId: "comfort",
		statement: "I take time to relax",
		isPrimary: false,
	},
	{
		id: "54",
		meaningId: "care",
		statement: "The wellbeing of others is very important to me",
		isPrimary: false,
	},
	{
		id: "55",
		meaningId: "attentiveness",
		statement: "At a birth, a wedding or a death it is important to perform certain rituals",
		isPrimary: false,
	},
	{
		id: "56",
		meaningId: "harmony",
		statement: "Creating a positive atmosphere is very important to me when I am together with other people",
		isPrimary: false,
	},
	{
		id: "59",
		meaningId: "social-commitment",
		statement: "Building a fair society is more important to me than financial gains",
		isPrimary: false,
	},
	{
		id: "60",
		meaningId: "religiosity",
		statement: "My religion gives me strength",
		isPrimary: true,
	},
	{
		id: "61",
		meaningId: "unity-with-nature",
		statement: "I do my bit to protect the environment",
		isPrimary: false,
	},
	{
		id: "62",
		meaningId: "self-knowledge",
		statement: "Even though it takes a lot of effort, I'm always in search of self-knowledge",
		isPrimary: false,
	},
	{
		id: "63",
		meaningId: "health",
		statement: "I think a healthy diet is of great importance",
		isPrimary: true,
	},
	{
		id: "64",
		meaningId: "generativity",
		statement: "I want to make a difference for the future",
		isPrimary: false,
	},
	{
		id: "65",
		meaningId: "spirituality",
		statement: "I believe in miracles",
		isPrimary: false,
	},
	{
		id: "66",
		meaningId: "development",
		statement: "I can immediately get very enthusiastic about new ideas",
		isPrimary: false,
	},
	{
		id: "67",
		meaningId: "challenge",
		statement: "Limits are there to be shattered",
		isPrimary: false,
	},
	{
		id: "68",
		meaningId: "power",
		statement: "I would prefer to lead a group rather than just be a member",
		isPrimary: false,
	},
	{
		id: "69",
		meaningId: "development",
		statement: "I am always on the lookout for tasks that will teach me something",
		isPrimary: true,
	},
	{
		id: "70",
		meaningId: "success",
		statement: "I need to produce excellent results",
		isPrimary: true,
	},
	{
		id: "71",
		meaningId: "freedom",
		statement: "I am a freedom-loving person",
		isPrimary: false,
	},
	{
		id: "72",
		meaningId: "knowledge",
		statement: "In my free time I have a thirst for knowledge about things I want to know more about",
		isPrimary: false,
	},
	{
		id: "73",
		meaningId: "creativity",
		statement: "I live my life imaginatively",
		isPrimary: false,
	},
	{
		id: "74",
		meaningId: "tradition",
		statement: "People shouldn't question tried and tested traditions",
		isPrimary: true,
	},
	{
		id: "75",
		meaningId: "practicality",
		statement: "Going through life with both feet firmly on the ground is very important to me",
		isPrimary: false,
	},
	{
		id: "76",
		meaningId: "moral",
		statement: "Everyone needs clear values to hold on to",
		isPrimary: true,
	},
	{
		id: "77",
		meaningId: "reason",
		statement: "I don't take decisions lightly but I take time to think them through",
		isPrimary: false,
	},
	{
		id: "78",
		meaningId: "community",
		statement: "I need to be around other people",
		isPrimary: true,
	},
	{
		id: "79",
		meaningId: "fun",
		statement: "People with whom I spend a lot of time should have a happy disposition",
		isPrimary: false,
	},
	{
		id: "80",
		meaningId: "love",
		statement: "I make a great effort to be intimate with a person I feel close to",
		isPrimary: false,
	},
	{
		id: "81",
		meaningId: "comfort",
		statement: "If I really want something, I treat myself to it",
		isPrimary: false,
	},
	{
		id: "82",
		meaningId: "care",
		statement: "I am always thinking of how I can make other people happy",
		isPrimary: true,
	},
	{
		id: "83",
		meaningId: "attentiveness",
		statement: "I want to experience every moment of my life to the full",
		isPrimary: true,
	},
	{
		id: "84",
		meaningId: "harmony",
		statement: "When dealing with other people harmony is very important to me",
		isPrimary: false,
	},
	{
		id: "87",
		meaningId: "social-commitment",
		statement: "I agree with increased petrol prices for the sake of the environment",
		isPrimary: false,
	},
	{
		id: "88",
		meaningId: "health",
		statement: "I try to make sure I have a balanced day",
		isPrimary: false,
	},
	{
		id: "89",
		meaningId: "unity-with-nature",
		statement: "I feel safe and sound in nature and the outdoors",
		isPrimary: false,
	},
	{
		id: "90",
		meaningId: "self-knowledge",
		statement: "It is very important for me to practice self-reflection",
		isPrimary: false,
	},
	{
		id: "91",
		meaningId: "comfort",
		statement: "Enjoying yourself is more important than health",
		isPrimary: false,
	},
	{
		id: "92",
		meaningId: "generativity",
		statement: "I try to create things of lasting value",
		isPrimary: false,
	},
	{
		id: "93",
		meaningId: "spirituality",
		statement: "There is a reason for everything happening the way it does",
		isPrimary: false,
	},
	{
		id: "94",
		meaningId: "challenge",
		statement: "I look for challenges",
		isPrimary: true,
	},
	{
		id: "95",
		meaningId: "individualism",
		statement: "I want to be different from other people",
		isPrimary: false,
	},
	{
		id: "96",
		meaningId: "power",
		statement: "I like to be able to influence other people",
		isPrimary: false,
	},
	{
		id: "97",
		meaningId: "development",
		statement: "Lifelong learning is important to me",
		isPrimary: false,
	},
	{
		id: "98",
		meaningId: "success",
		statement: "I am an achievement-orientated person",
		isPrimary: false,
	},
	{
		id: "99",
		meaningId: "freedom",
		statement: "I have a strong need for freedom",
		isPrimary: false,
	},
	{
		id: "100",
		meaningId: "knowledge",
		statement: "I want to be able to understand everything that crosses my path",
		isPrimary: false,
	},
	{
		id: "101",
		meaningId: "creativity",
		statement: "Creativity plays a very important role in my life",
		isPrimary: false,
	},
	{
		id: "102",
		meaningId: "tradition",
		statement: "Schools should present and teach values and not question them",
		isPrimary: false,
	},
	{
		id: "103",
		meaningId: "practicality",
		statement: "I am more of a doer than a thinker",
		isPrimary: false,
	},
	{
		id: "104",
		meaningId: "tradition",
		statement: "I need a sense of security in my life",
		isPrimary: false,
	},
	{
		id: "105",
		meaningId: "reason",
		statement: "I weigh up the pros and cons before taking a decision",
		isPrimary: false,
	},
	{
		id: "106",
		meaningId: "community",
		statement: "I spend as much time as possible in the company of other people",
		isPrimary: false,
	},
	{
		id: "107",
		meaningId: "fun",
		statement: "I feel more attracted to cheerful people than serious ones",
		isPrimary: false,
	},
	{
		id: "108",
		meaningId: "love",
		statement: "In my life everything revolves around love",
		isPrimary: false,
	},
	{
		id: "109",
		meaningId: "comfort",
		statement: "Whatever I do the most important thing is that I feel good doing it",
		isPrimary: false,
	},
	{
		id: "110",
		meaningId: "care",
		statement: "If someone asks me I'm always prepared to help",
		isPrimary: false,
	},
	{
		id: "111",
		meaningId: "attentiveness",
		statement: "At New Year I always take time to reflect on life",
		isPrimary: false,
	},
	{
		id: "112",
		meaningId: "harmony",
		statement: "I am striving for inner harmony",
		isPrimary: true,
	},
	{
		id: "115",
		meaningId: "social-commitment",
		statement: "I would be prepared to suffer financial losses for the sake of the environment",
		isPrimary: false,
	},
	{
		id: "116",
		meaningId: "harmony",
		statement: "I strive for inner peace and balance",
		isPrimary: false,
	},
	{
		id: "117",
		meaningId: "unity-with-nature",
		statement: "I only really feel alive when I'm outdoors in nature",
		isPrimary: false,
	},
	{
		id: "118",
		meaningId: "self-knowledge",
		statement: "I often think about who I am",
		isPrimary: false,
	},
	{
		id: "119",
		meaningId: "comfort",
		statement: "I do some things regularly because they make me feel good",
		isPrimary: false,
	},
	{
		id: "120",
		meaningId: "generativity",
		statement: "I try to make the world a better place to live in",
		isPrimary: true,
	},
	{
		id: "121",
		meaningId: "spirituality",
		statement: "I think that there is another reality to the one we already know",
		isPrimary: false,
	},
	{
		id: "122",
		meaningId: "challenge",
		statement: "I'm a person who likes to take risks",
		isPrimary: false,
	},
	{
		id: "123",
		meaningId: "individualism",
		statement: "It is my aim in life to discover and live out my abilities and interests",
		isPrimary: false,
	},
	{
		id: "124",
		meaningId: "power",
		statement: "When I get the opportunity I show my strengths",
		isPrimary: true,
	},
	{
		id: "125",
		meaningId: "development",
		statement: "I am always striving to change and improve myself",
		isPrimary: false,
	},
	{
		id: "126",
		meaningId: "attentiveness",
		statement: "There are things that I regularly do with others that have a special meaning for me",
		isPrimary: false,
	},
	{
		id: "127",
		meaningId: "freedom",
		statement: "I am driven by a desire for freedom",
		isPrimary: false,
	},
	{
		id: "128",
		meaningId: "knowledge",
		statement: "I read a lot",
		isPrimary: false,
	},
	{
		id: "129",
		meaningId: "creativity",
		statement: "In my free time I undertake creative activities",
		isPrimary: false,
	},
	{
		id: "130",
		meaningId: "tradition",
		statement: "Instead of looking for something new, I prefer the tried and tested",
		isPrimary: false,
	},
	{
		id: "131",
		meaningId: "practicality",
		statement: "People should always be realists",
		isPrimary: true,
	},
	{
		id: "132",
		meaningId: "moral",
		statement: "Parents should once again teach their children morals",
		isPrimary: false,
	},
	{
		id: "133",
		meaningId: "reason",
		statement: "I would describe myself as a sensible person",
		isPrimary: false,
	},
	{
		id: "134",
		meaningId: "community",
		statement: "Friendships are among the most important things in my life",
		isPrimary: false,
	},
	{
		id: "135",
		meaningId: "fun",
		statement: "It is important for me to laugh heartily at least once a day",
		isPrimary: true,
	},
	{
		id: "136",
		meaningId: "practicality",
		statement: "People should concentrate on the useful and necessary things in life",
		isPrimary: false,
	},
	{
		id: "137",
		meaningId: "comfort",
		statement: "I take enough time to laze around",
		isPrimary: false,
	},
	{
		id: "138",
		meaningId: "practicality",
		statement: "I prefer to learn things that are practical rather than theoretical",
		isPrimary: false,
	},
	{
		id: "139",
		meaningId: "attentiveness",
		statement: "I think it is important to experience the change of seasons and to celebrate them",
		isPrimary: false,
	},
	{
		id: "140",
		meaningId: "harmony",
		statement: "It is very important for me to live in harmony with myself and with others",
		isPrimary: false,
	},
	{
		id: "141",
		meaningId: "practicality",
		statement: "Actions speak louder than words",
		isPrimary: false,
	},
	{
		id: "142",
		meaningId: "attentiveness",
		statement: "Some things are so important to me that I celebrate them regularly",
		isPrimary: false,
	},
	{
		id: "143",
		meaningId: "harmony",
		statement: "I pay great attention to my inner equilibrium",
		isPrimary: false,
	},
	{
		id: "144",
		meaningId: "self-knowledge",
		statement: "I deliberately take time to think about myself",
		isPrimary: false,
	},
	{
		id: "145",
		meaningId: "spirituality",
		statement: "Everyone has a mission to fulfil in life",
		isPrimary: false,
	},
	{
		id: "146",
		meaningId: "individualism",
		statement: "Making my own way in life is crucial for me",
		isPrimary: false,
	},
	{
		id: "147",
		meaningId: "development",
		statement: "Life should mean development and change",
		isPrimary: false,
	},
	{
		id: "148",
		meaningId: "freedom",
		statement: "Freedom is the most important thing for me",
		isPrimary: true,
	},
	{
		id: "149",
		meaningId: "tradition",
		statement: "I like to hold onto traditions",
		isPrimary: false,
	},
	{
		id: "150",
		meaningId: "fun",
		statement: "I like to go out",
		isPrimary: false,
	},
	{
		id: "151",
		meaningId: "comfort",
		statement: "Now and then I really spoil myself and don't watch my finances as much as normally",
		isPrimary: false,
	},
];
